# Generated by Django 2.2 on 2019-06-11 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system_test_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Linpack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tester_name', models.CharField(max_length=100)),
                ('N', models.IntegerField(default=0)),
                ('NB', models.IntegerField(default=0)),
                ('PMAP', models.CharField(max_length=100)),
                ('P', models.IntegerField(default=0)),
                ('Q', models.IntegerField(default=0)),
                ('PFACT', models.CharField(max_length=30)),
                ('NBMIN', models.IntegerField(default=0)),
                ('NDIV', models.IntegerField(default=0)),
                ('RFACT', models.CharField(max_length=30)),
                ('BCAST', models.CharField(max_length=30)),
                ('DEPTH', models.IntegerField(default=0)),
                ('SWAP', models.CharField(max_length=50)),
                ('L1', models.CharField(max_length=30)),
                ('U', models.CharField(max_length=30)),
                ('EQUIL', models.CharField(max_length=10)),
                ('ALIGN', models.CharField(max_length=30)),
                ('actual_GFLOPS', models.CharField(max_length=30)),
                ('given_problem', models.CharField(max_length=150)),
                ('expected_answer', models.CharField(max_length=30)),
                ('answer_result', models.CharField(max_length=20)),
                ('date_added', models.DateTimeField(verbose_name='date added')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_test_app.System')),
            ],
        ),
    ]
